### ISSUE TITLE
Segmentation Demo

### ISSUE THREAD

**Issue by vngabriel** [itsprakhar/Downstream-Dinov2#1]
Hi, Prakhar, that is really good work. I'm trying to use DinoV2 for segmentation but I'm not succeeding. I hope you post the training and demo for segmentation.

**Comment by itsprakhar** [comment]
Hello @vngabriel thanks for creating the issue. I will sure add the training and demo code soon.

**Comment by itsprakhar** [comment]
I have added basic (Very basic, just to illustrate the process) code for training a dinov2 segmentation model. Please create a new issue if you need improvemnt.
